name: Render video
on:
  workflow_dispatch:
    inputs:
      tickerName:
        description: "Ticker Name"
        required: true
        default: "Bitcoin"
      strData:
        description: "Marker Data (EOD array)"
        required: true
        default: "[]"
      period:
        description: "Message under ticker name"
        required: true
        default: "graphique daily du 05/04 au 06/05"
      digit:
        description: "Number of digit"
        required: true
        default: 3

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run render -- --props="./input-props.json"
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out/video.mp4
